twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        APP_NAME: '%env(APP_NAME)%'
        APP_VERSION: '%env(APP_VERSION)%'
        APP_SEO_TITLE: '%env(APP_SEO_TITLE)%'
        APP_LINKEDIN_URL: '%env(APP_LINKEDIN_URL)%'
        APP_GITHUB_URL: '%env(APP_GITHUB_URL)%'
        APP_PHONE_NUMBER: '%env(APP_PHONE_NUMBER)%'
        APP_EMAIL_CONTACT: '%env(APP_EMAIL_CONTACT)%'
        APP_MAPS_API_KEY: '%env(APP_MAPS_API_KEY)%'

when@test:
    twig:
        strict_variables: true
